<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< HEAD
<testsuite ignored="0" hostname="MYSHEC644151L" failures="1" tests="2" name="Default test" time="8.979" errors="0" timestamp="2025-02-27T11:49:12 IST">
  <testcase classname="com.sun.tests.LoginTest" name="Testlogin" time="0.759"/>
  <testcase classname="com.sun.tests.LoginTest" name="Testlogin" time="0.567">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	 Login Failed please enter correct details expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
 Login Failed please enter correct details expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.sun.tests.LoginTest.Testlogin(LoginTest.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Testlogin -->
=======
<testsuite ignored="0" hostname="DESKTOP-EDQ2E72" failures="0" tests="3" name="Default test" time="11.505" errors="0" timestamp="2025-02-26T22:19:28 IST">
  <testcase classname="com.sun.tests.AddcartTest" name="clickonAddcart" time="2.25"/>
  <testcase classname="com.sun.tests.AddcartTest" name="clickonAddcart" time="2.063"/>
  <testcase classname="com.sun.tests.AddcartTest" name="clickonAddcart" time="2.095"/>
>>>>>>> branch 'master' of https://github.com/Rakeshnkholi/Info.git
</testsuite> <!-- Default test -->
